<?php
/** @var \SimpleMage\SimpleFavorites\Block\Template $block */

$productList = $block->getProductList();
$productCollection = $productList->getProductCollection();
$productRenderer = $block->getProductRenderer();
?>

<?php if (!$productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <div class="favorites favorites-grid products wrapper grid products-grid">
        <ol class="products list items product-items">
            <?php foreach ($productCollection as $product): ?>

            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $product->getId() ?>"
                     data-container="product-grid">
                    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= /* @noEscape */ $productRenderer->renderImage($product, 'category_page_grid') ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $productRenderer->renderName($product); ?>
                            </a>
                        </strong>

                        <?= /* @noEscape */ $productRenderer->renderPrice($product) ?>
                        <?php if ($product->isAvailable()):?>
                            <div class="stock available">
                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                        <?php else:?>
                            <div class="stock unavailable">
                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
        <?= $block->getChildBlock('product_list_toolbar')
                ->setIsBottom(true)
                ->setCollection($productCollection)
                ->toHtml()
        ?>
    </div>
<?php endif; ?>
